# .github/workflows/gpio_validator.yml
name: Build GPIO Validator on esp32

on:
  push:
    branches: [ main ]
    paths:
      - 'gpio_validator/**'
      - '.github/workflows/gpio_validator.yml'
  pull_request:
    paths:
      - 'gpio_validator/**'

jobs:
  build_esp32:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # PIP cache in local project folder to avoid permission issues with /github/home
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: gpio_validator/test/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # ESP-IDF build cache
      - name: Cache ESP-IDF Build
        uses: actions/cache@v4
        with:
          path: gpio_validator/test/build
          key: idf-build-esp32-${{ github.sha }}
          restore-keys: |
            idf-build-esp32-

      - name: Build GPIO Validator
        shell: bash
        working-directory: gpio_validator/test
        run: |
          . $IDF_PATH/export.sh
          
          # Instala usando a pasta de cache local que o root tem permiss√£o de escrita
          python -m pip install --cache-dir .cache/pip pytest-embedded-idf pytest-embedded-qemu
          
          idf.py set-target esp32
          idf.py build
