# .github/workflows/gpio_validator.yml
name: Build GPIO Validator Multi-Target

on:
  push:
    branches: [ main ]
    paths:
      - 'gpio_validator/**'
      - '.github/workflows/gpio_validator.yml'

jobs:
  build_targets:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5
    strategy:
      fail-fast: false
      matrix:
        idf_target: [esp32, esp32s3, esp32c3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # PIP cache
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: gpio_validator/test/.cache/pip
          key: ${{ runner.os }}-pip-pytest
      
      # Build cache for each TARGET
      - name: Cache ESP-IDF Build
        uses: actions/cache@v4
        with:
          path: gpio_validator/test/build
          # The key includes the target to avoid overwriting different targets' caches
          key: idf-build-${{ matrix.idf_target }}-${{ github.sha }}
          restore-keys: |
            idf-build-${{ matrix.idf_target }}-

      - name: Build GPIO Validator
        shell: bash
        working-directory: gpio_validator/test
        run: |
          . $IDF_PATH/export.sh
          
          python -m pip install --cache-dir .cache/pip pytest-embedded-idf pytest-embedded-qemu
          
          # Executes set-target to ensure configuration the first time
          # After the cache is "warm", you can comment this line
          idf.py set-target ${{ matrix.idf_target }}
          
          idf.py build
