# .github/workflows/gpio_validator.yml
name: Build GPIO Validator

on:
  push:
    branches: [ main ]
    paths:
      - 'gpio_validator/**'
      - '.github/workflows/gpio_validator.yml'
  pull_request:
    paths:
      - 'gpio_validator/**'

jobs:
  test_esp32:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache IDF build
        uses: actions/cache@v3
        with:
          path: gpio_validator/test/build
          key: idf-build-esp32-${{ hashFiles('gpio_validator/test/main/**') }}
          restore-keys: idf-build-esp32-

      - name: Build and Test ESP32
        shell: bash
        working-directory: gpio_validator/test
        run: |
          . $IDF_PATH/export.sh
          python -m pip install pytest-embedded-qemu pytest-embedded-idf
          
          idf.py set-target esp32
          idf.py build
          
          CUR_DIR=$(pwd)
          python -m esptool --chip esp32 merge_bin \
            -o $CUR_DIR/build/flash_image.bin \
            --fill-flash-size 4MB \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x1000 $CUR_DIR/build/bootloader/bootloader.bin \
            0x8000 $CUR_DIR/build/partition_table/partition-table.bin \
            0x10000 $CUR_DIR/build/test_gpio_validator.bin

          python -m pytest pytest_gpio_validator.py \
            --embedded-services qemu \
            --qemu-image build/flash_image.bin \
            -s